# General configuration settings
project_name: "Statistical Arbitrage Project"
log_level: "INFO"
data_directory: "data/"

# Trading bot settings
trading_bot:
  api_key: "your_api_key"
  api_secret: "your_api_secret"
  trading_pair: "BTC/USD"
  trade_quantity: 0.01
  max_exposure: 0.1

# Reinforcement learning settings
reinforcement_learning:
  state_size: 10
  action_size: 5
  learning_rate: 0.001
  epsilon: 0.1
  gamma: 0.95

# Model training settings
tensorflow:
  input_shape: 10
  epochs: 50
  batch_size: 32
  learning_rate: 0.001

pytorch:
  input_size: 10
  epochs: 50
  batch_size: 32
  learning_rate: 0.001

# Risk metrics settings
risk_free_rate: 0.02
confidence_level: 0.95
